# Polynomial Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Polynomial Regression model on the Training set

In [4]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

## Predicting the Test set results

In [5]:
y_pred = regressor.predict(poly_reg.transform(X_test))

In [6]:
errors = []
for i in range(len(y_test)):
    errors.append((y_test[i] - y_pred[i]) * 100 / y_test[i])
errors_array = np.array(errors).reshape(len(errors),1)

In [7]:
np.set_printoptions(precision = 2) # precision after . is 2
np.set_printoptions(suppress = True) #numpy array won't be printed with scientific notation
print(np.concatenate((y_pred.reshape(-1, 1), y_test.reshape(-1, 1), errors_array), axis=1))

[[433.94 431.23  -0.63]
 [457.9  460.01   0.46]
 [460.52 461.14   0.13]
 ...
 [469.53 473.26   0.79]
 [438.27 438.    -0.06]
 [461.67 463.28   0.35]]


## Evaluating the Model Performance

In [8]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9458193355773253