# Artificial Neural Network

### Importing the libraries

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [3]:
tf.__version__

'2.11.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [6]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

In [8]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
x[:, 2] = lb.fit_transform(x[:, 2])

Label Encoding the "Gender" column

In [9]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [14]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Part 2 - Building the ANN

### Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

### Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

### Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

## Part 3 - Training the ANN

### Compiling the ANN

In [19]:
ann.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

### Training the ANN on the Training set

In [20]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5546 - accuracy: 0.7560
Epoch 2/100
250/250 [==============================] - 0s 765us/step - loss: 0.4699 - accuracy: 0.8044
Epoch 3/100
250/250 [==============================] - 0s 892us/step - loss: 0.4365 - accuracy: 0.8120
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4108 - accuracy: 0.8219
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3905 - accuracy: 0.8320
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3772 - accuracy: 0.8409
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3689 - accuracy: 0.8451
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3633 - accuracy: 0.8491
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3593 - accuracy: 0.8495
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3566 - ac

250/250 [==============================] - 0s 805us/step - loss: 0.3337 - accuracy: 0.8627
Epoch 81/100
250/250 [==============================] - 0s 905us/step - loss: 0.3333 - accuracy: 0.8648
Epoch 82/100
250/250 [==============================] - 0s 780us/step - loss: 0.3335 - accuracy: 0.8630
Epoch 83/100
250/250 [==============================] - 0s 901us/step - loss: 0.3336 - accuracy: 0.8650
Epoch 84/100
250/250 [==============================] - 0s 781us/step - loss: 0.3335 - accuracy: 0.8619
Epoch 85/100
250/250 [==============================] - 0s 920us/step - loss: 0.3332 - accuracy: 0.8629
Epoch 86/100
250/250 [==============================] - 0s 782us/step - loss: 0.3334 - accuracy: 0.8627
Epoch 87/100
250/250 [==============================] - 0s 743us/step - loss: 0.3331 - accuracy: 0.8635
Epoch 88/100
250/250 [==============================] - 0s 773us/step - loss: 0.3333 - accuracy: 0.8626
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 101ms/step
[[False]]


**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [22]:
y_pred = ann.predict(x_test)
y_pred = y_pred > 0.5
print(np.concatenate((y_test.reshape(-1 ,1 ), y_pred.reshape(-1, 1)), axis = 1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[1511   84]
 [ 201  204]]
0.8575
