# Multiple Linear Regression

General template. To use just change the .csv file's name.

## Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dataset = pd.read_csv("Data.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## Training the Multiple Linear Regression model on the Training set

In [4]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

## Predicting the Test set results

In [5]:
y_pred = regressor.predict(x_test)

In [6]:
errors = []
for i in range(len(y_test)):
    errors.append((y_test[i] - y_pred[i]) * 100 / y_test[i])
errors_array = np.array(errors).reshape(len(errors),1)

In [7]:
np.set_printoptions(precision = 2) # precision after . is 2
np.set_printoptions(suppress = True) #numpy array won't be printed with scientific notation
print(np.concatenate((y_pred.reshape(-1, 1), y_test.reshape(-1, 1), errors_array), axis=1))

[[431.43 431.23  -0.05]
 [458.56 460.01   0.31]
 [462.75 461.14  -0.35]
 ...
 [469.52 473.26   0.79]
 [442.42 438.    -1.01]
 [461.88 463.28   0.3 ]]


Since dataset is too big, last approach to see how accurate is nonsense. Next function will give us R square value which give us a value from 0 to 1. The closer it is to one, the better the model.

## Evaluating the Model Performance

In [8]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))

0.9325315554761303
