# Natural Language Processing

## Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)

## Importing the dataset

In [3]:
dataset = pd.read_csv("Restaurant_Reviews.tsv", delimiter='\t', quoting = 3)

In [4]:
dataset.head(15)

Review  Liked
0                            Wow... Loved this place.      1
1                                  Crust is not good.      0
2           Not tasty and the texture was just nasty.      0
3   Stopped by during the late May bank holiday of...      1
4   The selection on the menu was great and so wer...      1
5      Now I am getting angry and I want my damn pho.      0
6               Honeslty it didn't taste THAT fresh.)      0
7   The potatoes were like rubber and you could te...      0
8                           The fries were great too.      1
9                                      A great touch.      1
10                           Service was very prompt.      1
11                                 Would not go back.      0
12  The cashier had no care what so ever on what I...      0
13  I tried the Cape Cod ravoli, chicken, with cra...      1
14  I was disgusted because I was pretty sure that...      0

## Cleaning the texts

In [5]:
import re #library for simplify the texts
import nltk #lib for downloading the stopwords and stem the texts
nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 1000):
    review = re.sub("[^a-zA-Z]", ' ', dataset["Review"][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stopword=stopwords.words("english")
    all_stopword.remove("not")
    review = [ps.stem(word) for word in review if word not in set(all_stopword)]
    review = " ".join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /home/furkan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [6]:
print(corpus)

['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price', 'get angri want damn pho', 'honeslti tast fresh', 'potato like rubber could tell made ahead time kept warmer', 'fri great', 'great touch', 'servic prompt', 'would not go back', 'cashier care ever say still end wayyy overpr', 'tri cape cod ravoli chicken cranberri mmmm', 'disgust pretti sure human hair', 'shock sign indic cash', 'highli recommend', 'waitress littl slow servic', 'place not worth time let alon vega', 'not like', 'burritto blah', 'food amaz', 'servic also cute', 'could care less interior beauti', 'perform', 'right red velvet cake ohhh stuff good', 'never brought salad ask', 'hole wall great mexican street taco friendli staff', 'took hour get food tabl restaur food luke warm sever run around like total overwhelm', 'worst salmon sashimi', 'also combo like burger fri beer decent deal', 'like final blow', 'found place accid could not

## Creating the Bag of Words model

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)
x = cv.fit_transform(corpus).toarray()
y = dataset["Liked"].values
print(len(x[0]))

1500


## Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

## Training the Naive Bayes model on the Training set

In [9]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

## Predicting the Test set results

In [10]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(-1 ,1), y_test.reshape(-1 , 1)), axis = 1))

[[1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]

## Making the Confusion Matrix

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [12]:
print(cm)
print(accuracy_score(y_test, y_pred))

[[55 42]
 [12 91]]
0.73


## Bonus: Testing all the classification models

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC, SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [14]:
def models(x, y):
    # Training of the Logistic Regression model
    log = LogisticRegression(random_state=0)
    log.fit(x, y)
    
    # Training of the KNN model
    knn = KNeighborsClassifier(n_neighbors = 10, metric = "minkowski", p = 2)
    knn.fit(x, y)
    
    # Training of the Linear SVM model
    svm1 = LinearSVC(max_iter = 10000, random_state = 0)
    svm1.fit(x, y)
    
    # Training of the RBF Kernel SVM model
    kernel_svm = SVC(kernel = "rbf", random_state = 0)
    kernel_svm.fit(x, y)
    
    # Training of the Naive Bayes
    naive = GaussianNB()
    naive.fit(x, y)
    
    # Training of the Decision Tree model
    dtree = DecisionTreeClassifier(criterion = "gini", random_state = 0)
    dtree.fit(x, y)
    
    # Training of the Random Forest model
    rforest = RandomForestClassifier(n_estimators = 70, criterion = "gini" ,random_state = 0)
    rforest.fit(x, y)
    
    print('[0]Logistic Regression Training Accuracy:', log.score(x, y))
    print('[1]K Nearest Neighbor Training Accuracy:', knn.score(x, y))
    print('[2]Support Vector Machine (Linear Classifier) Training Accuracy:', svm1.score(x, y))
    print('[3]Support Vector Machine (RBF Classifier) Training Accuracy:', kernel_svm.score(x, y))
    print('[4]Gaussian Naive Bayes Training Accuracy:', naive.score(x, y))
    print('[5]Decision Tree Classifier Training Accuracy:', dtree.score(x, y))
    print('[6]Random Forest Classifier Training Accuracy:', rforest.score(x, y))
    
    return log, knn, svm1, kernel_svm, naive, dtree, rforest

In [15]:
model = models(x_train, y_train)

[0]Logistic Regression Training Accuracy: 0.965
[1]K Nearest Neighbor Training Accuracy: 0.76375
[2]Support Vector Machine (Linear Classifier) Training Accuracy: 0.9925
[3]Support Vector Machine (RBF Classifier) Training Accuracy: 0.97375
[4]Gaussian Naive Bayes Training Accuracy: 0.92125
[5]Decision Tree Classifier Training Accuracy: 0.99625
[6]Random Forest Classifier Training Accuracy: 0.99625


In [16]:
for i in range(len(model)):
    print(confusion_matrix(y_test, model[i].predict(x_test)))
    print("Model[{}] Testing Accuracy".format(i),accuracy_score(y_test, model[i].predict(x_test)))
    print()

[[80 17]
 [28 75]]
Model[0] Testing Accuracy 0.775

[[85 12]
 [56 47]]
Model[1] Testing Accuracy 0.66

[[80 17]
 [25 78]]
Model[2] Testing Accuracy 0.79

[[89  8]
 [36 67]]
Model[3] Testing Accuracy 0.78

[[55 42]
 [12 91]]
Model[4] Testing Accuracy 0.73

[[77 20]
 [33 70]]
Model[5] Testing Accuracy 0.735

[[90  7]
 [39 64]]
Model[6] Testing Accuracy 0.77



## Bonus 2: Single prediction

In [17]:
new_review = "I hate this place"
new_review = re.sub("[^a-zA-Z]", " ", new_review)
new_review = new_review.lower()
new_review = new_review.split()
# we declared PorterStemmer above
# we declared all_stopwords above
new_review = [ps.stem(i) for i in new_review if not i in set(all_stopword)]
new_review = " ".join(new_review)
x_new = cv.transform([new_review]).toarray()
y_pred = classifier.predict(x_new)

In [18]:
print(y_pred)

[0]


In [19]:
new_review = "I loved this place"
new_review = re.sub("[^a-zA-Z]", " ", new_review)
new_review = new_review.lower()
new_review = new_review.split()
# we declared PorterStemmer above
# we declared all_stopwords above
new_review = [ps.stem(i) for i in new_review if not i in set(all_stopword)]
new_review = " ".join(new_review)
x_new = cv.transform([new_review]).toarray()
y_pred = classifier.predict(x_new)

In [20]:
print(y_pred)

[1]
