# NUMPY

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [3]:
print(type(my_list))

<class 'list'>


In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [5]:
print(type(np.array(my_list)))

<class 'numpy.ndarray'>


In [6]:
my_list = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
my_matrix = np.array(my_list)

In [8]:
my_matrix.shape

(3, 3)

In [9]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.ones((3,3)) + 5 #This usage is special to numpy arrays

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [13]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [14]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5,5)

array([[0.15181212, 0.20043187, 0.6357714 , 0.60931153, 0.51392484],
       [0.47700383, 0.87569834, 0.4975708 , 0.24633421, 0.48733355],
       [0.1753584 , 0.65965906, 0.02896586, 0.32279207, 0.65447663],
       [0.47443758, 0.15980224, 0.02759865, 0.33019773, 0.78846814],
       [0.53622804, 0.44203075, 0.3734448 , 0.17218374, 0.30130208]])

In [16]:
np.random.randn(10)

array([ 1.84329293, -0.42532471, -0.13645093, -0.81147115, -2.03956019,
        1.37038822, -0.52308776, -0.48227523,  0.73799216, -2.44561437])

In [17]:
np.random.normal(52)

52.65812519146579

In [18]:
np.random.randint(1,15,2)

array([11, 13])

In [19]:
np.random.seed(101) #seed local to this cell
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [20]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0,50,10)

In [24]:
ranarr

array([28,  0, 46,  5, 12, 29, 40, 49, 19, 47])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr.max()

49

In [27]:
ranarr.min()

0

In [28]:
ranarr.argmax() # it gives index location

7

In [29]:
ranarr.argmin()# it gives index location

1

In [30]:
ranarr.dtype

dtype('int64')

# ----------------------------------------------------------------

In [31]:
ranarr[7] #same as python lists

49

In [32]:
arr[1:5] #same as python lists

array([1, 2, 3, 4])

In [33]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
 arr /12

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667, 1.        , 1.08333333, 1.16666667,
       1.25      , 1.33333333, 1.41666667, 1.5       , 1.58333333,
       1.66666667, 1.75      , 1.83333333, 1.91666667, 2.        ])

In [36]:
arr - 24

array([-24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12,
       -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [37]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

# ----------------------------------------------------------------

In [38]:
arr = np.arange(0,10)

In [39]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
slice_of_arr = arr[0:6]

In [41]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [42]:
slice_of_arr[0:2] = 24

In [43]:
arr

array([24, 24,  2,  3,  4,  5,  6,  7,  8,  9])

In [44]:
arr_copy = arr.copy()

In [45]:
arr_copy

array([24, 24,  2,  3,  4,  5,  6,  7,  8,  9])

In [46]:
arr_copy[:] = 125

In [47]:
arr_copy

array([125, 125, 125, 125, 125, 125, 125, 125, 125, 125])

In [48]:
arr

array([24, 24,  2,  3,  4,  5,  6,  7,  8,  9])

# ----------------------------------------------------------------

### INDEXING on 2d array

In [49]:
arr_2d = np.array([[1,2,3], [4,5,6],  [7,8,9]])

In [50]:
arr_2d.shape

(3, 3)

In [51]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr_2d[2]

array([7, 8, 9])

In [53]:
arr_subset = arr_2d[0:-1, 1:]

In [54]:
arr_subset

array([[2, 3],
       [5, 6]])

In [55]:
arr = np.arange(1, 11)

In [56]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [58]:
arr < 12

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [59]:
bool_arr = arr > 4

In [60]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [61]:
arr[bool_arr] # new usage

array([ 5,  6,  7,  8,  9, 10])

In [62]:
arr[arr>4] # new usage

array([ 5,  6,  7,  8,  9, 10])

In [63]:
arr[arr == 2] # you can give any conditional expression to numpy array
#it will give the items that meet the conditions

array([2])

# ----------------------------------------------------------------

In [64]:
arr = np.arange(0, 10)

In [65]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
arr / arr

/tmp/ipykernel_5738/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [68]:
1 / arr

/tmp/ipykernel_5738/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [69]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [70]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [71]:
np.log(arr)

/tmp/ipykernel_5738/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [72]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [73]:
arr.sum()

45

In [74]:
arr.mean()

4.5

In [75]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr_2d.shape

(3, 3)

In [77]:
arr_2d.sum()

45

In [78]:
arr_2d.sum(axis = 1) # GIVE the sum, across the columns

array([ 6, 15, 24])

In [79]:
arr_2d.sum(axis = 0) # GIVE the sum, across the rows

array([12, 15, 18])